# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gomod"
    directory: "/bunx"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gomod"
    directory: "/dockertestx"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"
