linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unused

run:
  skip-dirs:
    - gen
    - design
